ALTER TABLE `spa_comments` CHANGE `iduser` `iduser` INT(10) UNSIGNED NULL DEFAULT NULL, CHANGE `idsale` `idsale` INT(10) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `spa_comments` ADD FOREIGN KEY (`idsale`) REFERENCES `spa_sales`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT; ALTER TABLE `spa_comments` ADD FOREIGN KEY (`iduser`) REFERENCES `spa_users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
