ALTER TABLE `spa_users` CHANGE `birth` `birth` DATE NULL DEFAULT NULL, CHANGE `logged` `logged` DATETIME NULL DEFAULT NULL, CHANGE `image` `image` VARCHAR(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `newsletter` `newsletter` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1', CHANGE `address` `address` VARCHAR(127) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `addressobs` `addressobs` VARCHAR(127) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `zipcode` `zipcode` VARCHAR(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `city` `city` VARCHAR(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `social` `social` VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `idprovince` `idprovince` SMALLINT(5) UNSIGNED NULL DEFAULT NULL, CHANGE `phone` `phone` VARCHAR(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE `active` `active` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0', CHANGE `dni` `dni` INT(10) UNSIGNED NULL DEFAULT NULL;


UPDATE spa_users 
SET image=NULL
WHERE image='';


ALTER TABLE `spa_users` CHANGE `lastname` `lastname` VARCHAR(80) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL;


ALTER TABLE `spa_sessions` ADD FOREIGN KEY (`iduser`) REFERENCES `spa_users`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
